// ════════════════════════════════════════════════════════════
// NM Jewellers — Storefront + Admin Logic
// Firebase connection lives in firebase-config.js (edit that
// file with your real project keys — do NOT edit this file
// to connect Firebase).
// ════════════════════════════════════════════════════════════
import {
  db, auth,
  collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, deleteDoc,
  onSnapshot, serverTimestamp, query, orderBy, limit, where,
  signInWithEmailAndPassword, signOut, onAuthStateChanged
} from './firebase-config.js';


// ════════════════════════════════════════════
// GLOBAL STATE
// ════════════════════════════════════════════
let PRODS    = [];   // live from Firestore
let RATES    = { gold24:7420, gold22:6803, gold18:5565, silver:89.5 };
let SETTINGS = {
  storeName:'NM Jewellers', gst:'27XXXXX1234X1Z5',
  phone:'+91 98765 43210', whatsapp:'919876543210',
  email:'info@nmjewellers.in', city:'Pune',
  address:'Saraf Bazar , Bhusawal – 425201',
  hours:'Mon-Sun: 10:00 AM – 8:00 PM | Tuesday: Closed',
  tagline:'Since1 2016 · BIS Hallmarked'
};
let CART     = [];
let WISHLIST = new Set();
let FILT     = [];
let HERO_IDX = 0;
let IS_ADMIN = false;

// ════════════════════════════════════════════
// PRICE ENGINE
// ════════════════════════════════════════════
function getRate(metal){
  if(metal.includes('24K')) return RATES.gold24;
  if(metal.includes('22K')) return RATES.gold22;
  if(metal.includes('18K')) return RATES.gold18;
  if(metal.includes('Silver')) return RATES.silver;
  return RATES.gold18;
}
function calcPrice(p){
  const r=getRate(p.metal), mv=p.wt*r, mk=p.wt*p.mc, sub=mv+mk, gst=sub*.03, tot=sub+gst;
  return {r,mv,mk,gst,tot};
}
function fmt(n){ return '₹'+Math.round(n).toLocaleString('en-IN'); }

// ════════════════════════════════════════════
// FIRESTORE — REAL-TIME LISTENERS
// ════════════════════════════════════════════
function startListeners(){
  // Products — live sync
  onSnapshot(query(collection(db,'products'), orderBy('id')), snap => {
    PRODS = snap.docs.map(d => ({...d.data(), _docId: d.id}));
    FILT  = [...PRODS];
    renderFeatured();
    renderMain();
    if(IS_ADMIN){ renderAdminProducts(); renderInventory(); renderTopProducts(); updateDashStats(); }
  });

  // Rates — live sync
  onSnapshot(doc(db,'rates','current'), snap => {
    if(snap.exists()){
      const d = snap.data();
      RATES = { gold24:d.gold24, gold22:d.gold22, gold18:d.gold18, silver:d.silver };
      updateRateTicker();
      if(IS_ADMIN) updateAdminRateDisplay();
    }
  });

  // Settings — live sync
  onSnapshot(doc(db,'settings','store'), snap => {
    if(snap.exists()){
      SETTINGS = {...SETTINGS, ...snap.data()};
      applySettings();
    }
  });

  // Orders — admin only (called after login)
}

function listenOrders(){
  onSnapshot(query(collection(db,'orders'), orderBy('createdAt','desc'), limit(50)), snap => {
    const orders = snap.docs.map(d => ({...d.data(), _docId:d.id}));
    renderOrderTables(orders);
    updateDashStats();
  });
}

// ════════════════════════════════════════════
// FIRESTORE — WRITE OPERATIONS
// ════════════════════════════════════════════
async function fbSaveProduct(p){
  try {
    await setDoc(doc(db,'products',p.id), {
      id:p.id, name:p.name, cat:p.cat, metal:p.metal,
      wt:parseFloat(p.wt), mc:parseFloat(p.mc), stock:parseInt(p.stock),
      tag:p.tag||'', img:p.img, desc:p.desc,
      updatedAt: serverTimestamp()
    });
    return true;
  } catch(e){ toast('❌ Error: '+e.message); return false; }
}

async function fbDeleteProduct(docId){
  try { await deleteDoc(doc(db,'products',docId)); return true; }
  catch(e){ toast('❌ Error: '+e.message); return false; }
}

async function fbUpdateStock(docId, newStock){
  try {
    await updateDoc(doc(db,'products',docId), { stock:newStock, updatedAt:serverTimestamp() });
    return true;
  } catch(e){ toast('❌ '+e.message); return false; }
}

async function fbSaveRates(r){
  try {
    await setDoc(doc(db,'rates','current'), { ...r, updatedAt:serverTimestamp() });
    return true;
  } catch(e){ toast('❌ '+e.message); return false; }
}

async function fbSaveSettings(s){
  try {
    await setDoc(doc(db,'settings','store'), { ...s, updatedAt:serverTimestamp() });
    return true;
  } catch(e){ toast('❌ '+e.message); return false; }
}

async function fbPlaceOrder(orderData){
  try {
    const ref = await addDoc(collection(db,'orders'), {
      ...orderData, status:'Pending', createdAt:serverTimestamp()
    });
    // Reduce stock for each cart item
    for(const item of CART){
      const prod = PRODS.find(p=>p.id===item.id);
      if(prod && prod.stock > 0){
        await fbUpdateStock(prod._docId, prod.stock - 1);
      }
    }
    return ref.id;
  } catch(e){ toast('❌ Order error: '+e.message); return null; }
}

async function fbUpdateOrderStatus(docId, status){
  try {
    await updateDoc(doc(db,'orders',docId), { status, updatedAt:serverTimestamp() });
    toast('✅ Order status updated to: '+status);
  } catch(e){ toast('❌ '+e.message); }
}

// ════════════════════════════════════════════
// SEED DATA — run once to populate Firebase
// ════════════════════════════════════════════
async function seedFirebase(){
  if(!IS_ADMIN){ toast('Login as admin first'); return; }
  const SEED = [
    {id:'NMJ-001',name:'Royal Peacock Gold Necklace',cat:'Necklaces',metal:'Gold 22K',wt:28.5,mc:550,stock:3,tag:'Bestseller',img:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80',desc:'Handcrafted peacock motif necklace in 22K BIS Hallmarked gold with intricate filigree work.'},
    {id:'NMJ-002',name:'Solitaire Diamond Engagement Ring',cat:'Gold Rings',metal:'Gold 18K',wt:4.8,mc:1200,stock:6,tag:'New',img:'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80',desc:'Elegant 0.25ct VS clarity solitaire diamond ring in 18K white gold. IGI certified.'},
    {id:'NMJ-003',name:'Grand Bridal Jewellery Set',cat:'Bridal Sets',metal:'Gold 22K',wt:95.0,mc:650,stock:2,tag:'Bridal',img:'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80',desc:'Complete 5-piece bridal set in 22K BIS Hallmarked gold.'},
    {id:'NMJ-004',name:'Classic Plain Gold Bangles (Pair)',cat:'Bangles',metal:'Gold 22K',wt:22.4,mc:350,stock:14,tag:'',img:'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80',desc:'Traditional plain gold bangles (pair) in 22K hallmarked gold.'},
    {id:'NMJ-005',name:'Diamond Jhumka Earrings',cat:'Earrings',metal:'Gold 18K',wt:8.2,mc:900,stock:5,tag:'New',img:'https://images.unsplash.com/photo-1573408301185-9519f94816b5?w=600&q=80',desc:'Opulent jhumka earrings with VS clarity diamond accents in 18K gold.'},
    {id:'NMJ-006',name:'Sterling Silver Oxidised Choker',cat:'Silver',metal:'Silver 925',wt:45.0,mc:80,stock:18,tag:'',img:'https://images.unsplash.com/photo-1589128777073-263566ae5e4d?w=600&q=80',desc:'Handcrafted 925 sterling silver oxidised choker with Rajasthani tribal motifs.'},
    {id:'NMJ-007',name:'Lakshmi Temple Gold Pendant',cat:'Pendants',metal:'Gold 22K',wt:9.5,mc:450,stock:0,tag:'Sold Out',img:'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80',desc:'Traditional Goddess Lakshmi temple pendant in 22K gold with ruby and pearl accents.'},
    {id:'NMJ-008',name:'Emerald Cocktail Gold Ring',cat:'Gold Rings',metal:'Gold 18K',wt:6.2,mc:800,stock:4,tag:'',img:'https://images.unsplash.com/photo-1615655406736-b37887a66b17?w=600&q=80',desc:'Statement cocktail ring with 1.8ct natural Colombian emerald in 18K gold.'},
    {id:'NMJ-009',name:'Gold Mangalsutra with Diamond',cat:'Mangalsutra',metal:'Gold 22K',wt:7.2,mc:380,stock:9,tag:'',img:'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&q=80',desc:'Traditional 22K gold mangalsutra with black beads and diamond pendant.'},
    {id:'NMJ-010',name:'Rose Gold Diamond Bracelet',cat:'Bangles',metal:'Gold 18K',wt:11.4,mc:750,stock:3,tag:'New',img:'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&q=80',desc:'Elegant rose gold bracelet with certified diamond accents in 18K gold.'},
    {id:'NMJ-011',name:'Kundan Meenakari Gold Earrings',cat:'Earrings',metal:'Gold 22K',wt:12.5,mc:600,stock:7,tag:'',img:'https://images.unsplash.com/photo-1524813686514-a57563d77965?w=600&q=80',desc:'Traditional kundan meenakari earrings in 22K gold with handpainted enamel work.'},
    {id:'NMJ-012',name:'Diamond Solitaire Pendant',cat:'Diamond',metal:'Gold 18K',wt:3.2,mc:950,stock:5,tag:'',img:'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=600&q=80',desc:'0.30ct IGI certified solitaire diamond pendant in 18K white gold.'},
  ];
  toast('🔄 Seeding database...');
  for(const p of SEED){ await fbSaveProduct(p); }
  await fbSaveRates({gold24:7420,gold22:6803,gold18:5565,silver:89.5,mode:'manual'});
  await fbSaveSettings(SETTINGS);
  toast('✅ Database seeded with '+SEED.length+' products!');
}
window.seedFirebase = seedFirebase;

// ════════════════════════════════════════════
// AUTH
// ════════════════════════════════════════════
onAuthStateChanged(auth, user => {
  IS_ADMIN = !!user;
  if(user){
    document.getElementById('adminLogin').classList.remove('on');
    document.getElementById('adminView').style.display = 'flex';
    document.getElementById('store').style.display = 'none';
    document.getElementById('waFloat').style.display = 'none';
    refreshAdmin();
    listenOrders();
  }
});

window.doLogin = async function(){
  const email = document.getElementById('al-u').value.trim();
  const pass  = document.getElementById('al-p').value;
  if(!email||!pass){ toast('Enter email and password'); return; }
  try {
    document.getElementById('alBtn').textContent = 'Signing in...';
    await signInWithEmailAndPassword(auth, email, pass);
  } catch(e){
    document.getElementById('alErr').style.display = 'block';
    document.getElementById('alErr').textContent = 'Wrong credentials: '+e.message;
    document.getElementById('alBtn').textContent = 'Sign In';
  }
};

window.doLogout = async function(){
  await signOut(auth);
  IS_ADMIN = false;
  document.getElementById('adminView').style.display = 'none';
  document.getElementById('store').style.display = 'block';
  document.getElementById('waFloat').style.display = 'flex';
  applySettings();
  renderFeatured();
  renderMain();
};

window.openAL  = () => document.getElementById('adminLogin').classList.add('on');
window.closeAL = () => document.getElementById('adminLogin').classList.remove('on');

// ════════════════════════════════════════════
// PAGE ROUTING
// ════════════════════════════════════════════
window.goP = function(pg){
  document.querySelectorAll('.pg').forEach(p=>p.classList.remove('on'));
  const el = document.getElementById('pg-'+pg);
  if(el){ el.classList.add('on'); window.scrollTo({top:0,behavior:'smooth'}); }
  if(pg==='home')    renderFeatured();
  if(pg==='listing') renderMain();
};

window.fGo = function(cat){
  FILT = cat==='all' ? [...PRODS] : PRODS.filter(p=>p.cat===cat);
  const t = cat==='all'?'All Jewellery':cat;
  const el1=document.getElementById('lTitle'), el2=document.getElementById('lbread'), el3=document.getElementById('lCount');
  if(el1) el1.textContent=t;
  if(el2) el2.textContent=t;
  if(el3) el3.textContent='Showing '+FILT.length+' products';
  goP('listing');
  setTimeout(()=>{
    document.querySelectorAll('.f-tab').forEach(t=>t.classList.remove('on'));
    document.querySelectorAll('.f-tab').forEach(t=>{
      if(t.textContent.trim()===cat||(cat==='all'&&t.textContent.trim()==='All')) t.classList.add('on');
    });
    renderMain();
  },50);
};

// ════════════════════════════════════════════
// PRODUCT RENDERING
// ════════════════════════════════════════════
function pCard(p, idx){
  const pr   = calcPrice(p);
  const inW  = WISHLIST.has(p.id);
  const sC   = p.stock===0?'av-out':p.stock<=3?'av-low':'av-in';
  const sL   = p.stock===0?'Out of Stock':p.stock<=3?'Only '+p.stock+' left':'In Stock';
  const tgH  = p.tag ? `<div class="prod-tag${p.tag==='New'||p.tag==='Bridal'?' new':p.tag==='Sold Out'?' sold':''}">${p.tag}</div>` : '';
  return `<div class="prod-cell" onclick="openDet('${p.id}')">
    <div class="prod-img-wrap">
      <img src="${p.img}" alt="${p.name}" loading="lazy" onerror="this.src='https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80'">
      ${tgH}
      <button class="prod-wish${inW?' on':''}" onclick="toggleWish(event,'${p.id}')">
        <svg viewBox="0 0 24 24" fill="${inW?'currentColor':'none'}" stroke="currentColor" stroke-width="1.8"><path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/></svg>
      </button>
      <div class="prod-hover-bar">
        <button class="prod-hbtn" onclick="event.stopPropagation();addCart('${p.id}')">${p.stock===0?'NOTIFY ME':'ADD TO CART'}</button>
        <button class="prod-hbtn sec" onclick="event.stopPropagation();openDet('${p.id}')">VIEW DETAILS</button>
      </div>
    </div>
    <div class="prod-body">
      <div class="prod-cat">${p.cat}</div>
      <div class="prod-name">${p.name}</div>
      <div class="prod-tags-row"><span class="prod-tag-chip">${p.metal}</span><span class="prod-tag-chip">${p.wt}g</span></div>
      <div class="prod-price-row">
        <div><span class="prod-price">${fmt(pr.tot)}</span><span class="prod-gst"> incl. GST</span></div>
        <span class="prod-avail ${sC}">${sL}</span>
      </div>
    </div>
  </div>`;
}

function renderFeatured(){
  const g = document.getElementById('featGrid');
  if(g) g.innerHTML = PRODS.length
    ? PRODS.slice(0,8).map(p=>pCard(p)).join('')
    : '<div style="grid-column:1/-1;text-align:center;padding:40px;color:#888">Loading products...</div>';
}

function renderMain(){
  const g = document.getElementById('mainGrid');
  if(g) g.innerHTML = FILT.length
    ? FILT.map(p=>pCard(p)).join('')
    : '<div style="grid-column:1/-1;text-align:center;padding:60px;color:#888">No products found</div>';
}

window.filterP = function(cat, btn){
  document.querySelectorAll('.f-tab').forEach(t=>t.classList.remove('on'));
  if(btn) btn.classList.add('on');
  FILT = cat==='all' ? [...PRODS] : PRODS.filter(p=>p.cat===cat);
  const lT=document.getElementById('lTitle'), lC=document.getElementById('lCount');
  if(lT) lT.textContent = cat==='all'?'All Jewellery':cat;
  if(lC) lC.textContent = 'Showing '+FILT.length+' products';
  renderMain();
};

window.sortP = function(v){
  if(v==='low')  FILT.sort((a,b)=>calcPrice(a).tot-calcPrice(b).tot);
  if(v==='high') FILT.sort((a,b)=>calcPrice(b).tot-calcPrice(a).tot);
  if(v==='name') FILT.sort((a,b)=>a.name.localeCompare(b.name));
  renderMain();
};

// ════════════════════════════════════════════
// PRODUCT DETAIL
// ════════════════════════════════════════════
window.openDet = function(prodId){
  const p = PRODS.find(x=>x.id===prodId);
  if(!p) return;
  const pr  = calcPrice(p);
  const pur = p.metal.includes('22K')?'22 Karat (91.6%)':p.metal.includes('18K')?'18 Karat (75%)':p.metal.includes('24K')?'24 Karat (99.9%)':p.metal;
  const imgs = p.imgs || [p.img,p.img,p.img,p.img];
  document.getElementById('detCont').innerHTML = `
    <div class="detail-wrap">
      <div class="detail-bc"><a onclick="goP('home')">Home</a>›<a onclick="fGo('${p.cat}')">${p.cat}</a>›<span>${p.name}</span></div>
      <div class="detail-layout">
        <div class="det-gal-sticky">
          <div class="det-main-img"><img src="${imgs[0]}" id="dImg" alt="${p.name}" onerror="this.src='${p.img}'"></div>
          <div class="det-thumbs">${imgs.map((img,i)=>`<div class="det-thumb${i===0?' on':''}" onclick="setThumb(this,'${img}')"><img src="${img}" alt="${p.name}" onerror="this.src='${p.img}'"></div>`).join('')}</div>
        </div>
        <div>
          <div style="font-size:10px;letter-spacing:2.5px;text-transform:uppercase;color:var(--text3);margin-bottom:8px;font-weight:700">${p.cat}</div>
          <h1 style="font-family:'Playfair Display',serif;font-size:24px;font-weight:500;line-height:1.3;margin-bottom:8px">${p.name}</h1>
          <div class="det-sku">Design: <strong>${p.id}</strong><span>BIS Hallmarked</span><span>Certificate Included</span></div>
          <div class="price-box">
            <h3 style="font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--gold2);font-weight:700;margin-bottom:12px">Price Breakdown</h3>
            <table class="ptable">
              <tr><td>Metal Rate (${p.metal})</td><td>${fmt(pr.r)} / gram</td></tr>
              <tr><td>Gross Weight</td><td>${p.wt} grams</td></tr>
              <tr><td>Metal Value</td><td>${fmt(pr.mv)}</td></tr>
              <tr><td>Making Charges (₹${p.mc}/g)</td><td>${fmt(pr.mk)}</td></tr>
              <tr><td>GST @ 3%</td><td>${fmt(pr.gst)}</td></tr>
              <tr class="ptotal"><td>Total Price</td><td>${fmt(pr.tot)}</td></tr>
            </table>
          </div>
          <div class="det-specs">
            <div class="spec"><div class="spec-k">Metal</div><div class="spec-v">${p.metal}</div></div>
            <div class="spec"><div class="spec-k">Purity</div><div class="spec-v">${pur}</div></div>
            <div class="spec"><div class="spec-k">Gross Weight</div><div class="spec-v">${p.wt}g</div></div>
            <div class="spec"><div class="spec-k">Hallmark</div><div class="spec-v">BIS Certified</div></div>
            <div class="spec"><div class="spec-k">Availability</div><div class="spec-v ${p.stock===0?'av-out':p.stock<=3?'av-low':'av-in'}">${p.stock===0?'Out of Stock':p.stock<=3?'Only '+p.stock+' left':'In Stock ('+p.stock+')'}</div></div>
            <div class="spec"><div class="spec-k">Shipping</div><div class="spec-v">Free &amp; Insured</div></div>
          </div>
          <p style="font-size:13.5px;color:var(--text2);line-height:1.8;margin-bottom:18px">${p.desc}</p>
          <div class="det-actions">
            <button class="btn-addcart" onclick="addCart('${p.id}')" ${p.stock===0?'disabled':''}>
              ${p.stock===0?'OUT OF STOCK — NOTIFY ME':'ADD TO CART'}
            </button>
            <a class="btn-wa-enq" href="https://wa.me/${SETTINGS.whatsapp}?text=Hi!%20I'm%20interested%20in%20${encodeURIComponent(p.name)}%20(${p.id})" target="_blank">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg>
              ENQUIRE ON WHATSAPP
            </a>
          </div>
          <div class="trust-row">
            <div class="trust-item"><svg viewBox="0 0 24 24" fill="none" stroke="var(--maroon)" stroke-width="1.8"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>BIS Hallmarked</div>
            <div class="trust-item"><svg viewBox="0 0 24 24" fill="none" stroke="var(--maroon)" stroke-width="1.8"><path d="M5 12h14M12 5l7 7-7 7"/></svg>Free Shipping</div>
            <div class="trust-item"><svg viewBox="0 0 24 24" fill="none" stroke="var(--maroon)" stroke-width="1.8"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 11-2.12-9.36L23 10"/></svg>30-Day Returns</div>
          </div>
        </div>
      </div>
    </div>`;
  goP('detail');
};

window.setThumb = function(el,img){
  document.querySelectorAll('.det-thumb').forEach(t=>t.classList.remove('on'));
  el.classList.add('on');
  const di=document.getElementById('dImg'); if(di) di.src=img;
};

// ════════════════════════════════════════════
// CART
// ════════════════════════════════════════════
window.openCart  = () => { document.getElementById('cartBg').classList.add('on'); document.getElementById('cartDrawer').classList.add('on'); renderCart(); };
window.closeCart = () => { document.getElementById('cartBg').classList.remove('on'); document.getElementById('cartDrawer').classList.remove('on'); };

window.addCart = function(prodId){
  const p = PRODS.find(x=>x.id===prodId);
  if(!p||p.stock===0){ toast('This item is out of stock'); return; }
  if(!CART.find(c=>c.id===p.id)) CART.push({...p});
  updBadge(); toast('✅ Added: '+p.name);
};

window.removeCart = function(id){
  CART = CART.filter(c=>c.id!==id); renderCart(); updBadge();
};

function updBadge(){
  const n=CART.length;
  const el=document.getElementById('cCount'); if(el) el.textContent=n;
  const bd=document.getElementById('cBadge'); if(bd) bd.textContent=n+' item'+(n!==1?'s':'');
}

function renderCart(){
  const body=document.getElementById('cartBody'), ft=document.getElementById('cartFt');
  if(!CART.length){
    body.innerHTML=`<div class="cart-empty"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 01-8 0"/></svg><h3>Your cart is empty</h3><p>Add jewellery to start shopping</p><button class="btn-hero" style="margin-top:14px" onclick="closeCart();fGo('all')">Shop Now</button></div>`;
    ft.classList.add('hide'); return;
  }
  ft.classList.remove('hide');
  body.innerHTML=CART.map(p=>{
    const pr=calcPrice(p);
    return `<div class="c-item"><div class="c-item-img"><img src="${p.img}" alt="${p.name}" onerror="this.src='${p.img}'"></div><div class="c-item-body"><div class="c-item-name">${p.name}</div><div class="c-item-meta">${p.metal} · ${p.wt}g · ${p.id}</div><div class="c-item-price">${fmt(pr.tot)}</div></div><button class="c-item-rm" onclick="removeCart('${p.id}')">✕</button></div>`;
  }).join('');
  const totEl=document.getElementById('cartTot');
  if(totEl) totEl.textContent=fmt(CART.reduce((s,p)=>s+calcPrice(p).tot,0));
}

// ════════════════════════════════════════════
// WISHLIST
// ════════════════════════════════════════════
window.toggleWish = function(e,id){
  e.stopPropagation();
  WISHLIST.has(id)?WISHLIST.delete(id):WISHLIST.add(id);
  toast(WISHLIST.has(id)?'♥ Saved to wishlist':'Removed from wishlist');
  const b=document.getElementById('wCount');
  if(b){ b.textContent=WISHLIST.size; b.classList.toggle('hide',WISHLIST.size===0); }
  renderFeatured(); renderMain();
};

// ════════════════════════════════════════════
// CHECKOUT
// ════════════════════════════════════════════
window.openCo = function(){
  closeCart();
  const tot=CART.reduce((s,p)=>s+calcPrice(p).tot,0);
  const sumEl=document.getElementById('coSum');
  if(sumEl) sumEl.innerHTML=CART.map(p=>`<div class="co-sum-r"><span>${p.name}</span><span>${fmt(calcPrice(p).tot)}</span></div>`).join('')+`<div class="co-sum-r tot"><span>Total (incl. GST)</span><span>${fmt(tot)}</span></div>`;
  document.getElementById('coMain').classList.remove('hide');
  document.getElementById('coDone').classList.add('hide');
  document.getElementById('coModal').classList.add('on');
};
window.closeCo = () => document.getElementById('coModal').classList.remove('on');
window.selPay  = el => { document.querySelectorAll('.pay-opt').forEach(o=>o.classList.remove('on')); el.classList.add('on'); };

window.placeOrder = async function(){
  const fname = document.getElementById('cf1')?.value.trim();
  const phone = document.getElementById('cf3')?.value.trim();
  const addr  = document.getElementById('cf4')?.value.trim();
  if(!fname||!phone||!addr){ toast('Please fill in all delivery details'); return; }
  const btn = document.querySelector('#coMain .btn-place');
  if(btn) btn.textContent='Placing Order...';
  const orderData = {
    customer: { name:fname+' '+(document.getElementById('cf2')?.value||''), phone, address:addr+', '+(document.getElementById('cf5')?.value||'')+' '+(document.getElementById('cf6')?.value||'') },
    items: CART.map(p=>({ id:p.id, name:p.name, metal:p.metal, wt:p.wt, price:Math.round(calcPrice(p).tot) })),
    total: Math.round(CART.reduce((s,p)=>s+calcPrice(p).tot,0)),
    paymentMethod: document.querySelector('.pay-opt.on')?.textContent||'Card',
  };
  const orderId = await fbPlaceOrder(orderData);
  if(orderId){
    CART=[]; updBadge();
    document.getElementById('coMain').classList.add('hide');
    document.getElementById('coDone').classList.remove('hide');
    const oid=document.getElementById('orderId'); if(oid) oid.textContent='Order #'+orderId.slice(-6).toUpperCase()+' Confirmed';
    if(btn) btn.textContent='PLACE ORDER & PAY SECURELY';
  }
};

// ════════════════════════════════════════════
// RATE TICKER
// ════════════════════════════════════════════
function updateRateTicker(){
  const ids=[['t24',RATES.gold24],['t22',RATES.gold22],['t18',RATES.gold18],['tsv',RATES.silver]];
  ids.forEach(([id,val])=>{ const el=document.getElementById(id); if(el) el.textContent=fmt(val); });
  const rt=document.getElementById('rTime'); if(rt) rt.textContent=' · Updated: '+new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});
}

// ════════════════════════════════════════════
// SETTINGS APPLY
// ════════════════════════════════════════════
function applySettings(){
  const s=SETTINGS;
  const txt=(id,v)=>{ const el=document.getElementById(id); if(el) el.textContent=v; };
  txt('dyn-logo-name',  s.storeName);
  txt('dyn-storename',  s.storeName);
  txt('dyn-footer-name',s.storeName);
  txt('dyn-gst',        s.gst);
  txt('dyn-phone',      s.phone);
  txt('dyn-email',      s.email);
  txt('dyn-addr-short', s.address);
  const wafab=document.getElementById('dyn-wa-fab');
  if(wafab) wafab.href='https://wa.me/'+s.whatsapp+'?text=Hi%20'+encodeURIComponent(s.storeName)+'!';
  document.title = s.storeName+' – Gold, Diamond & Bridal Jewellery | Since 1982';
}

// ════════════════════════════════════════════
// HERO CAROUSEL
// ════════════════════════════════════════════
window.heroMove = function(d){
  const n=document.querySelectorAll('.hero-slide').length;
  HERO_IDX=(HERO_IDX+d+n)%n;
  const t=document.getElementById('heroTrack'); if(t) t.style.transform=`translateX(-${HERO_IDX*100}%)`;
  document.querySelectorAll('.hdot').forEach((dt,i)=>dt.classList.toggle('on',i===HERO_IDX));
};

// ════════════════════════════════════════════
// ADMIN PANEL
// ════════════════════════════════════════════
window.aPage = function(pg,el){
  document.querySelectorAll('.av-pg').forEach(p=>p.classList.remove('on'));
  const apEl=document.getElementById('ap-'+pg); if(apEl) apEl.classList.add('on');
  document.querySelectorAll('.av-link').forEach(l=>l.classList.remove('on'));
  if(el) el.classList.add('on');
  if(pg==='settings') syncSettingsForm();
};

function refreshAdmin(){
  updateDashStats();
  updateAdminRateDisplay();
  renderAdminProducts();
  renderInventory();
  renderTopProducts();
  const d=document.getElementById('avDate');
  if(d) d.textContent=new Date().toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
  const c=document.getElementById('avClock');
  if(c) c.textContent=new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});
  // Build revenue chart
  const months=['Oct','Nov','Dec','Jan','Feb','Mar'], vals=[8.2,9.4,14.1,10.8,11.5,14.2], mx=Math.max(...vals);
  const chart=document.getElementById('avChart');
  if(chart) chart.innerHTML=months.map((m,i)=>`<div class="av-bar-w"><div class="av-bar" style="height:${(vals[i]/mx)*100}px"></div><span class="av-bar-lbl">${m}</span></div>`).join('');
}

function updateDashStats(){
  const dp=document.getElementById('d-p'); if(dp) dp.textContent=PRODS.length;
  const dl=document.getElementById('d-l'); if(dl) dl.textContent=PRODS.filter(p=>p.stock>0&&p.stock<=3).length;
}

function updateAdminRateDisplay(){
  const ag24=document.getElementById('ag24'); if(ag24) ag24.textContent=fmt(RATES.gold24);
  const ag22=document.getElementById('ag22'); if(ag22) ag22.textContent=fmt(RATES.gold22);
  const asv=document.getElementById('asv');   if(asv)  asv.textContent='₹'+RATES.silver;
}

function renderAdminProducts(){
  const tbl=document.getElementById('ptable');
  if(!tbl) return;
  tbl.innerHTML=PRODS.map(p=>{
    const pr=calcPrice(p), sc=p.stock===0?'out':p.stock<=3?'low':'in', sl=p.stock===0?'Out':p.stock<=3?'Low ('+p.stock+')':'In Stock';
    return `<tr>
      <td>${p.id}</td>
      <td style="display:flex;align-items:center;gap:9px;color:rgba(255,255,255,.8)"><img src="${p.img}" style="width:32px;height:32px;object-fit:cover" onerror="this.style.display='none'">${p.name}</td>
      <td style="color:rgba(255,255,255,.45)">${p.cat}</td>
      <td style="color:rgba(255,255,255,.45)">${p.metal}</td>
      <td style="color:rgba(255,255,255,.45)">${p.wt}g</td>
      <td style="color:var(--gold);font-weight:700">${fmt(pr.tot)}</td>
      <td><span class="a-pill ${sc}">${sl}</span></td>
      <td>
        <button class="av-btn-o" style="padding:4px 12px;font-size:10px;margin-right:4px" onclick="openEdit('${p.id}')">Edit</button>
        <button class="av-btn-d" onclick="confirmDelete('${p.id}','${p.name}')">Del</button>
      </td>
    </tr>`;
  }).join('');
}

function renderInventory(){
  const iI=PRODS.filter(p=>p.stock>3).length, lO=PRODS.filter(p=>p.stock>0&&p.stock<=3).length, oO=PRODS.filter(p=>p.stock===0).length;
  ['inv-i','inv-l','inv-o','inv-t'].forEach((id,i)=>{ const el=document.getElementById(id); if(el) el.textContent=[iI,lO,oO,PRODS.length][i]; });
  const tbl=document.getElementById('inv-table');
  if(!tbl) return;
  tbl.innerHTML=PRODS.map(p=>{
    const sc=p.stock===0?'out':p.stock<=3?'low':'in', sl=p.stock===0?'Out of Stock':p.stock<=3?'Low Stock':'In Stock';
    const pct=Math.min(100,(p.stock/15)*100), bc=p.stock===0?'#f88':p.stock<=3?'#f6a623':'#6fcf97';
    return `<tr>
      <td>${p.id}</td><td style="color:rgba(255,255,255,.75)">${p.name}</td>
      <td style="color:rgba(255,255,255,.4)">${p.cat}</td>
      <td style="color:#fff;font-weight:700">${p.stock}
        <div style="height:4px;background:rgba(255,255,255,.07);border-radius:2px;overflow:hidden;margin-top:4px"><div style="width:${pct}%;height:100%;background:${bc};border-radius:2px"></div></div>
      </td>
      <td><span class="a-pill ${sc}">${sl}</span></td>
      <td>
        <input type="number" value="${p.stock}" id="si-${p.id}" style="width:52px;background:rgba(255,255,255,.07);border:1px solid #2e2e2e;color:#fff;padding:5px 8px;font-size:12px">
        <button class="av-btn" style="padding:5px 12px;font-size:10px;margin-left:6px" onclick="setStock('${p.id}','${p._docId}')">Set</button>
      </td>
    </tr>`;
  }).join('');
}

window.setStock = async function(prodId, docId){
  const inp=document.getElementById('si-'+prodId);
  if(!inp) return;
  const n=parseInt(inp.value);
  if(isNaN(n)||n<0){ toast('❌ Enter a valid number'); return; }
  const ok = await fbUpdateStock(docId, n);
  if(ok) toast('✅ Stock for '+prodId+' updated to '+n+' — saved to database!');
};

window.confirmDelete = async function(prodId, name){
  if(!confirm('Delete "'+name+'"?\nThis permanently removes it from your store and database.')) return;
  const p=PRODS.find(x=>x.id===prodId);
  if(!p){ toast('Product not found'); return; }
  const ok=await fbDeleteProduct(p._docId);
  if(ok) toast('✅ "'+name+'" deleted from store and database.');
};

function renderTopProducts(){
  const el=document.getElementById('topP');
  if(!el) return;
  const sorted=[...PRODS].sort((a,b)=>calcPrice(b).tot-calcPrice(a).tot).slice(0,4);
  el.innerHTML=sorted.map((p,i)=>`<div style="display:flex;align-items:center;gap:10px;padding:9px;background:rgba(255,255,255,.04);border:1px solid #242424"><span style="font-family:'Playfair Display',serif;font-size:16px;font-weight:700;color:var(--gold);width:20px">${i+1}</span><img src="${p.img}" style="width:32px;height:32px;object-fit:cover" onerror="this.style.display='none'"><span style="font-size:12px;color:rgba(255,255,255,.6);flex:1">${p.name}</span><span style="font-family:'Playfair Display',serif;font-size:14px;color:var(--gold);font-weight:600">${fmt(calcPrice(p).tot)}</span></div>`).join('');
}

function renderOrderTables(orders){
  const sc={Pending:'pending',Shipped:'shipped',Delivered:'delivered',Cancelled:'cancelled'};
  const rowFn = (o,showAction) => `<tr>
    <td>#${o._docId?.slice(-6).toUpperCase()||'--'}</td>
    <td style="color:rgba(255,255,255,.65)">${o.customer?.name||'--'}</td>
    <td style="color:rgba(255,255,255,.65)">${o.items?.map(i=>i.name).join(', ').slice(0,30)||'--'}</td>
    <td style="color:var(--gold);font-weight:700">₹${o.total?.toLocaleString('en-IN')||'--'}</td>
    <td><span class="a-pill ${sc[o.status]||'pending'}">${o.status||'Pending'}</span></td>
    <td style="color:rgba(255,255,255,.3)">${o.createdAt?.toDate?.().toLocaleDateString('en-IN')||'--'}</td>
    ${showAction?`<td>
      <select onchange="fbUpdateOrderStatus('${o._docId}',this.value)" style="background:#222;border:1px solid #333;color:#fff;padding:4px 8px;font-size:11px;font-family:'Lato',sans-serif">
        <option ${o.status==='Pending'?'selected':''}>Pending</option>
        <option ${o.status==='Shipped'?'selected':''}>Shipped</option>
        <option ${o.status==='Delivered'?'selected':''}>Delivered</option>
        <option ${o.status==='Cancelled'?'selected':''}>Cancelled</option>
      </select>
    </td>`:''}
  </tr>`;
  const dEl=document.getElementById('d-orders');  if(dEl) dEl.innerHTML=orders.slice(0,5).map(o=>rowFn(o,false)).join('');
  const aEl=document.getElementById('all-o');      if(aEl) aEl.innerHTML=orders.map(o=>rowFn(o,true)).join('');
  // Update dashboard orders count
  const doEl=document.getElementById('dash-order-count'); if(doEl) doEl.textContent=orders.filter(o=>o.status==='Pending').length+' pending';
}
window.fbUpdateOrderStatus = fbUpdateOrderStatus;

// ════════════════════════════════════════════
// ADMIN — SAVE RATES
// ════════════════════════════════════════════
window.saveRates = async function(){
  const g24=parseFloat(document.getElementById('pc24')?.value)||RATES.gold24;
  const g22=parseFloat(document.getElementById('pc22')?.value)||RATES.gold22;
  const g18=parseFloat(document.getElementById('pc18')?.value)||RATES.gold18;
  const sv =parseFloat(document.getElementById('pcsv')?.value)||RATES.silver;
  const ok = await fbSaveRates({gold24:g24,gold22:g22,gold18:g18,silver:sv,mode:'manual'});
  if(ok) toast('✅ Metal rates saved to database! All prices updated across the store.');
};

window.autoCalc = function(){
  const g24=parseFloat(document.getElementById('pc24')?.value)||7420;
  const el22=document.getElementById('pc22'), el18=document.getElementById('pc18');
  if(el22) el22.value=Math.round(g24*.9166);
  if(el18) el18.value=Math.round(g24*.75);
};

// ════════════════════════════════════════════
// ADMIN — SETTINGS
// ════════════════════════════════════════════
function syncSettingsForm(){
  const s=SETTINGS;
  const f=(id,v)=>{ const el=document.getElementById(id); if(el) el.value=v; };
  f('s-name', s.storeName); f('s-gst',  s.gst);
  f('s-phone',s.phone);     f('s-wa',   s.whatsapp);
  f('s-email',s.email);     f('s-city', s.city);
  f('s-addr', s.address);   f('s-hours',s.hours);
}

window.saveSettings = async function(){
  const v=(id)=>{ const el=document.getElementById(id); return el?el.value.trim():''; };
  const newSettings = {
    storeName: v('s-name') || SETTINGS.storeName,
    gst:       v('s-gst')  || SETTINGS.gst,
    phone:     v('s-phone')|| SETTINGS.phone,
    whatsapp:  v('s-wa').replace(/[^0-9]/g,'') || SETTINGS.whatsapp,
    email:     v('s-email')|| SETTINGS.email,
    city:      v('s-city') || SETTINGS.city,
    address:   v('s-addr') || SETTINGS.address,
    hours:     v('s-hours')|| SETTINGS.hours,
  };
  SETTINGS = {...SETTINGS, ...newSettings};
  const ok = await fbSaveSettings(newSettings);
  if(ok){
    applySettings();
    const msg=document.getElementById('s-saved-msg');
    if(msg){
      msg.textContent='✅ Saved to database! '+SETTINGS.storeName+' | '+SETTINGS.phone;
      msg.style.display='block';
      setTimeout(()=>msg.style.display='none',6000);
    }
    toast('✅ Settings saved to Firebase! Changes are permanent and live.');
  }
};

// ════════════════════════════════════════════
// ADMIN — ADD PRODUCT
// ════════════════════════════════════════════
window.toggleAddF = () => document.getElementById('addF').classList.toggle('hide');

window.addProduct = async function(){
  const nm=document.getElementById('f-nm')?.value.trim();
  if(!nm){ toast('❌ Enter product name'); return; }
  const img=document.getElementById('f-img')?.value.trim()||'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80';
  const newP = {
    id:   document.getElementById('f-id')?.value.trim()||'NMJ-'+Date.now().toString().slice(-5),
    name: nm,
    cat:  document.getElementById('f-cat')?.value||'Gold Rings',
    metal:document.getElementById('f-met')?.value||'Gold 22K',
    wt:   parseFloat(document.getElementById('f-wt')?.value)||10,
    mc:   parseFloat(document.getElementById('f-mc')?.value)||400,
    stock:parseInt(document.getElementById('f-stk')?.value)||0,
    tag:  document.getElementById('f-tag')?.value||'',
    img:  img, imgs:[img,img,img,img],
    desc: document.getElementById('f-desc')?.value.trim()||'Premium quality jewellery by NM Jewellers.',
  };
  const ok = await fbSaveProduct(newP);
  if(ok){
    toggleAddF();
    ['f-id','f-nm','f-wt','f-mc','f-stk','f-img','f-desc'].forEach(id=>{ const el=document.getElementById(id); if(el) el.value=''; });
    toast('✅ "'+nm+'" added to catalogue and database! Visible on store now.');
  }
};

// ════════════════════════════════════════════
// EDIT PRODUCT MODAL
// ════════════════════════════════════════════
window.openEdit = function(prodId){
  const p=PRODS.find(x=>x.id===prodId);
  if(!p) return;
  const f=(id,v)=>{ const el=document.getElementById(id); if(el) el.value=v; };
  f('edit-docid', p._docId); f('edit-id',p.id); f('edit-nm',p.name);
  f('edit-cat',p.cat);       f('edit-met',p.metal);
  f('edit-wt',p.wt);         f('edit-mc',p.mc);
  f('edit-stk',p.stock);     f('edit-tag',p.tag||'');
  f('edit-img',p.img);       f('edit-desc',p.desc||'');
  updateEditPreview();
  document.getElementById('editModal').style.display='flex';
};
window.closeEdit = () => document.getElementById('editModal').style.display='none';

window.updateEditPreview = function(){
  const met=document.getElementById('edit-met')?.value||'Gold 22K';
  const wt=parseFloat(document.getElementById('edit-wt')?.value)||0;
  const mc=parseFloat(document.getElementById('edit-mc')?.value)||0;
  const rate=met.includes('24K')?RATES.gold24:met.includes('22K')?RATES.gold22:met.includes('18K')?RATES.gold18:met.includes('Silver')?RATES.silver:RATES.gold18;
  const mv=wt*rate, mk=wt*mc, s=mv+mk, gst=s*.03, tot=s+gst;
  const set=(id,v)=>{ const el=document.getElementById(id); if(el) el.textContent=v; };
  set('ep-mv',fmt(mv)); set('ep-mk',fmt(mk)); set('ep-gst',fmt(gst)); set('ep-tot',fmt(tot));
};

window.saveEdit = async function(){
  const docId=document.getElementById('edit-docid')?.value;
  const nm=document.getElementById('edit-nm')?.value.trim();
  if(!nm||!docId){ toast('Missing data'); return; }
  const img=document.getElementById('edit-img')?.value.trim()||'';
  const updated = {
    id:   document.getElementById('edit-id')?.value.trim(),
    name: nm,
    cat:  document.getElementById('edit-cat')?.value,
    metal:document.getElementById('edit-met')?.value,
    wt:   parseFloat(document.getElementById('edit-wt')?.value)||0,
    mc:   parseFloat(document.getElementById('edit-mc')?.value)||0,
    stock:parseInt(document.getElementById('edit-stk')?.value)||0,
    tag:  document.getElementById('edit-tag')?.value||'',
    img:  img, imgs:[img,img,img,img],
    desc: document.getElementById('edit-desc')?.value.trim()||'',
  };
  try {
    await updateDoc(doc(db,'products',docId), {...updated, updatedAt:serverTimestamp()});
    closeEdit();
    toast('✅ "'+nm+'" updated in database! Live on store.');
  } catch(e){ toast('❌ '+e.message); }
};

// ════════════════════════════════════════════
// MARQUEE
// ════════════════════════════════════════════
function buildMarquee(){
  const items=['BIS Hallmarked Gold','Free Insured Shipping','30-Day Returns','Transparent Pricing','Certified Diamonds','Expert Craftsmanship','Since 1982','Lifetime Buyback','10,000+ Happy Families'];
  const html=items.map(i=>`<span class="mq-item">${i}</span>`).join('');
  const el=document.getElementById('marqT'); if(el) el.innerHTML=html+html;
}

// ════════════════════════════════════════════
// TOAST
// ════════════════════════════════════════════
let tTimer;
window.toast = function(m){
  const el=document.getElementById('toast'); if(!el) return;
  el.textContent=m; el.classList.add('on');
  clearTimeout(tTimer); tTimer=setTimeout(()=>el.classList.remove('on'),3500);
};

// ════════════════════════════════════════════
// INIT
// ════════════════════════════════════════════
document.addEventListener('DOMContentLoaded', () => {
  // Build hero dots
  const n=document.querySelectorAll('.hero-slide').length;
  const dotsEl=document.getElementById('heroDots');
  if(dotsEl) dotsEl.innerHTML=Array.from({length:n},(_,i)=>`<button class="hdot${i===0?' on':''}" onclick="HERO_IDX=${i-1};heroMove(1)"></button>`).join('');
  setInterval(()=>heroMove(1), 5000);

  buildMarquee();
  applySettings();

  // Start Firebase listeners
  startListeners();

  // Admin clock
  setInterval(()=>{
    const c=document.getElementById('avClock'); if(c) c.textContent=new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});
  }, 30000);
});
